application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      schedulecron:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:18
        triggers:
          everyMin:
            feed: /whisk.system/alarms/interval
            inputs:
              minutes: 1
          rules:
            everyMinRule:
              trigger: everyMin
              action: generic
